### ISSUE TITLE
This app cannot be enabled because it makes the server unstable

### ISSUE THREAD

**Issue by ne20002** [UP-NextPush/server-app#16]
I get this error when trying to download and activate the app.

![grafik](https://user-images.githubusercontent.com/39007279/175769747-03142e93-007f-4153-9626-442434ae5ae1.png)

Nextcloud docker image 
Nextcloud 23.0.6

**Comment by p1gp1g** [comment]
A related issue : 
https://github.com/nextcloud/news/issues/89

From the quoted issue, the problem seems to come from your configuration.

You may want to install manually then (https://github.com/UP-NextPush/server-app#development)

PS: Please write your issues in english. You may need to set your language to english for screenshots too

**Comment by p1gp1g** [comment]
Is there any error related to this issue in your nextcloud.log ?
